CREATE TABLE episodes (
    id SERIAL PRIMARY KEY,
    painting_index INT,
    img_src VARCHAR(255),
    painting_title VARCHAR(255),
    season INT,
    episode_number INT,
    num_colors INT,
    youtube_src VARCHAR(255),
    broadcast_date DATE,
    special_guest BOOLEAN
);

CREATE TABLE colors (
    id SERIAL PRIMARY KEY,
    episode_id INT REFERENCES episodes(id),
    color_name VARCHAR(255),
    color_hex VARCHAR(7)
);

CREATE TABLE subjects (
    id SERIAL PRIMARY KEY,
    episode_id INT REFERENCES episodes(id),
    apple_frame BOOLEAN,
    aurora_borealis BOOLEAN,
    barn BOOLEAN,
    beach BOOLEAN,
    boat BOOLEAN,
    bridge BOOLEAN,
    building BOOLEAN,
    bushes BOOLEAN,
    cabin BOOLEAN,
    cactus BOOLEAN,
    circle_frame BOOLEAN,
    cirrus BOOLEAN,
    cliff BOOLEAN,
    clouds BOOLEAN,
    conifer BOOLEAN,
    cumulus BOOLEAN,
    deciduous BOOLEAN,
    diane_andre BOOLEAN,
    dock BOOLEAN,
    double_oval_frame BOOLEAN,
    farm BOOLEAN,
    fence BOOLEAN,
    fire BOOLEAN,
    florida_frame BOOLEAN,
    flowers BOOLEAN,
    fog BOOLEAN,
    framed BOOLEAN,
    grass BOOLEAN,
    guest BOOLEAN,
    half_circle_frame BOOLEAN,
    half_oval_frame BOOLEAN,
    hills BOOLEAN,
    lake BOOLEAN,
    lakes BOOLEAN,
    lighthouse BOOLEAN,
    mill BOOLEAN,
    moon BOOLEAN,
    mountain BOOLEAN,
    mountains BOOLEAN,
    night BOOLEAN,
    ocean BOOLEAN,
    oval_frame BOOLEAN,
    palm_trees BOOLEAN,
    path BOOLEAN,
    person BOOLEAN,
    portrait BOOLEAN,
    rectangle_3d_frame BOOLEAN,
    rectangular_frame BOOLEAN,
    river BOOLEAN,
    rocks BOOLEAN,
    seashell_frame BOOLEAN,
    snow BOOLEAN,
    snowy_mountain BOOLEAN,
    split_frame BOOLEAN,
    steve_ross BOOLEAN,
    structure BOOLEAN,
    sun BOOLEAN,
    tomb_frame BOOLEAN,
    tree BOOLEAN,
    trees BOOLEAN,
    triple_frame BOOLEAN,
    waterfall BOOLEAN,
    waves BOOLEAN,
    windmill BOOLEAN,
    window_frame BOOLEAN,
    winter BOOLEAN,
    wood_framed BOOLEAN
);
